services:
  infra:
    build: .
    ports:
      - "8001:8001"
    restart: always
    env_file: .env
    working_dir: /app
    volumes:
      - ./src:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    # gunicorn main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8001